   <script> -> <imports> <funcdecls>
  <imports> -> <import> <imports>
             | ε
   <import> -> string -> id stmtend
<funcdecls> -> <funcdecl> <funcdecls>
             | ε
 <funcdecl> -> id <argdecls> := <expr>
 <argdecls> -> id <argdecls>
             | ε
     <expr> -> <func> <args> stmtend
             | { <exprs> } stmtend
             | switch <expr> { <switches> }
     <args> -> <single> <args>
             | ε
    <exprs> -> <expr> <exprs>
             | ε
 <switches> -> <expr> := <expr> <switches>
             | default := <expr> <switches>
             | ε
   <single> -> <func>
             | number
             | string
             | <array>
             | { <exprs> }
    <array> -> [ <exprs> ]
     <func> -> id <subfunc>
  <subfunc> -> . id
             | ε

# vim: et
